version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: movie-list/app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
    restart: always
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}